//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class_weekday
    {
        public int class_id { get; set; }
        public int weekday_id { get; set; }
        public string hours { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Weekday Weekday { get; set; }
    }
}
