//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Class()
        {
            this.Class_student = new HashSet<Class_student>();
            this.Class_weekday = new HashSet<Class_weekday>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> start_day { get; set; }
        public Nullable<System.DateTime> end_day { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> teacher_id { get; set; }
        public Nullable<int> course_id { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Teacher Teacher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Class_student> Class_student { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Class_weekday> Class_weekday { get; set; }
    }
}
